/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hl55Hcj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
// import { Button } from "@/components/ui/button"
import { GetTaskList } from "./getTaskList"
import { InputField } from "./InputField"
import { Task } from "@/app/page";
import { getTask } from "@/app/action";

export async function Component() {

  const taskList: Task[] = await getTask('http://127.0.0.1:8000/todo/')
  console.log(taskList);

  return (
    <div className="bg-gray-100 dark:bg-gray-800 min-h-screen">
      <main className="max-w-4xl mx-auto p-6">
        <h1 className="text-3xl font-semibold text-center mb-6">Todo App</h1>
        <div className="bg-white dark:bg-gray-900 shadow-md rounded-lg p-6 mb-6">
          <InputField text="Add" />
          <GetTaskList taskList={taskList} />
        </div>
      </main>


      <footer className="bg-white dark:bg-gray-900 shadow px-6 py-4 flex justify-center items-center">
        <p className="text-gray-800 dark:text-gray-100">Created by Vercel</p>
        <img
          alt="Vercel Logo"
          className="rounded-full ml-4"
          height="40"
          src="/placeholder.svg"
          style={{
            aspectRatio: "40/40",
            objectFit: "cover",
          }}
          width="40"
        />
      </footer>
    </div>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}


function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function UndoIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 7v6h6" />
      <path d="M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13" />
    </svg>
  )
}
